mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

mail.smtp.user=issmfsistema@gmail.com
mail.smtp.password=evgp wbti enro sphx

email.equipa.1=1251666@isep.ipp.pt
email.equipa.2=1251943@isep.ipp.pt
email.equipa.3=1220492@isep.ipp.pt
email.equipa.4=1251663@isep.ipp.pt
email.equipa.5=email.do.professor@isep.ipp.pt